### ISSUE TITLE
6264 CE pin

### ISSUE THREAD

**Issue by Dale-Lien** [electrickery/ROM-emulator#1]
Hi,
In emuPod schematic, the 6264 pin 24 is A9, not CE, the 6264 only have one CE on pin 26, and have one /CE on pin 20.

**Comment by electrickery** [comment]
Hi Dale-Lien,
You are quite right, the files are outdated, the emuPod (for 24 pin devices) does not support the 6264, but the new emuPod28 does. The new files have the pin 24  issue fixed.
The software/firmware is also updated.
Greeting,
Fred Jan

**Comment by Dale-Lien** [comment]
Hi electrickery,
Thanks for your answer.
